version: '3.8'
services:
  ml_app:
    build:
      context: .
    container_name: ml_app
    command: ["bash_cmd/start.sh", "${PORT}"]
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    network_mode: host
